### ISSUE TITLE
Question: How to start playing a channel using JSONRPC

### ISSUE THREAD

**Issue by AThomsen** [xbmc-danish-addons/plugin.video.drnu#116]
I want to create a script in Home Assistant that
1. Turns on the TV
2. Set source to Kodi
3. Starts playing DR2

I believe I can do point 3 with a JSONRPC from Home Assistant, but I have no idea what the payload would be.

Anyone done something like this?

Thanks!

**Comment by TermeHansen** [comment]
I use home assistant, so I can see if make an example...

**Comment by TermeHansen** [comment]
![Image](https://github.com/user-attachments/assets/ff287c40-c3b7-4c0f-bf64-b30305f027d0)

or as YAML
```
sequence:
  - action: media_player.play_media
    data:
      media_content_type: URL
      media_content_id: plugin://plugin.video.drnu?playVideo=1&kids=1&idpath=/kanal/20875
    target:
      entity_id: media_player.osmc4
```

My kodi entity is called "osmc4" 😸
